package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTicketUserUse;
import org.linlinjava.litemall.db.domain.LitemallTicketUserUseExample;

public interface LitemallTicketUserUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    long countByExample(LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int insert(LitemallTicketUserUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTicketUserUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    LitemallTicketUserUse selectOneByExample(LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    LitemallTicketUserUse selectOneByExampleSelective(@Param("example") LitemallTicketUserUseExample example, @Param("selective") LitemallTicketUserUse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    List<LitemallTicketUserUse> selectByExampleSelective(@Param("example") LitemallTicketUserUseExample example, @Param("selective") LitemallTicketUserUse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    List<LitemallTicketUserUse> selectByExample(LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    LitemallTicketUserUse selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTicketUserUse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    LitemallTicketUserUse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    LitemallTicketUserUse selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTicketUserUse record, @Param("example") LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTicketUserUse record, @Param("example") LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTicketUserUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTicketUserUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTicketUserUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user_use
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}