package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderOrder;
import org.linlinjava.litemall.db.domain.LitemallOrderOrderExample;

public interface LitemallOrderOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int insert(LitemallOrderOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    LitemallOrderOrder selectOneByExample(LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    LitemallOrderOrder selectOneByExampleSelective(@Param("example") LitemallOrderOrderExample example, @Param("selective") LitemallOrderOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    List<LitemallOrderOrder> selectByExampleSelective(@Param("example") LitemallOrderOrderExample example, @Param("selective") LitemallOrderOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    List<LitemallOrderOrder> selectByExample(LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    LitemallOrderOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallOrderOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    LitemallOrderOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    LitemallOrderOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderOrder record, @Param("example") LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderOrder record, @Param("example") LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallOrderOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}