package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallBottleUser;
import org.linlinjava.litemall.db.domain.LitemallBottleUserExample;

public interface LitemallBottleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int insert(LitemallBottleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallBottleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    LitemallBottleUser selectOneByExample(LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    LitemallBottleUser selectOneByExampleSelective(@Param("example") LitemallBottleUserExample example, @Param("selective") LitemallBottleUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    List<LitemallBottleUser> selectByExampleSelective(@Param("example") LitemallBottleUserExample example, @Param("selective") LitemallBottleUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    List<LitemallBottleUser> selectByExample(LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    LitemallBottleUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallBottleUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    LitemallBottleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    LitemallBottleUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallBottleUser record, @Param("example") LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallBottleUser record, @Param("example") LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallBottleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallBottleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallBottleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bottle_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}