package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTicketUser;
import org.linlinjava.litemall.db.domain.LitemallTicketUserExample;

public interface LitemallTicketUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int insert(LitemallTicketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTicketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    LitemallTicketUser selectOneByExample(LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    LitemallTicketUser selectOneByExampleSelective(@Param("example") LitemallTicketUserExample example, @Param("selective") LitemallTicketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    List<LitemallTicketUser> selectByExampleSelective(@Param("example") LitemallTicketUserExample example, @Param("selective") LitemallTicketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    List<LitemallTicketUser> selectByExample(LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    LitemallTicketUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTicketUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    LitemallTicketUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    LitemallTicketUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTicketUser record, @Param("example") LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTicketUser record, @Param("example") LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTicketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTicketUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTicketUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_ticket_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}